### ISSUE TITLE
100% CPU load when script is run in "stdin/stdout" mode

### ISSUE THREAD

**Issue by amellinger** [bernie-skipole/indipydriver#2]
**Describe the bug**
When running the `example1.py` script in "stdin/stdout" mode the CPU load goes to 100%.

**To Reproduce**
1. Download "example1.py"
2. Comment out the `IPyServer` lines and add `asyncio.run(driver.asyncrun())` as last line.
3. Run `python3 example1.py`
4. CPU load goes to 100%

**Expected behavior**
With the `asyncio.sleep()` instructions I would have expected a rather low CPU load.

**Desktop (please complete the following information):**
 - OS: Ubuntu Mate 22.04 on Raspberry Pi; also Kubuntu 22.04 on amd64

**Comment by bernie-skipole** [comment]
Yes, I've tried it and get the same, and nowhere near that load when listening on a port, so I guess the method of using stdin/out is at fault. I'll see if I can find anything.

**Comment by bernie-skipole** [comment]
Fix applied, now works fine on my PC.
Published on Pypi as version 1.3.5

**Comment by amellinger** [comment]
Thanks, that fix resolves the issue.

**Comment by bernie-skipole** [comment]
Found the same problem when ipyserver had a remote connection to another server added. That is now fixed in version 1.3.6
